version: "3.7"

services:
  mysql:
    image: mysql:latest
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      default:
        aliases:
          - database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: amonic_airlines

  server:
    container_name: server
    restart: on-failure
    build:
      context: .
      dockerfile: server/Dockerfile
    networks:
      - default
    depends_on:
      - mysql
    ports:
      - "3000:3000"

volumes:
  mysql-data:
